# Generated by Django 3.1.7 on 2021-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20210324_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
